repos:

  - repo: local
    hooks:

    - id: enforce-conventional-commits
      name: Enforce Conventional Commits
      language: system
      verbose: true
      entry: |
        bash -c " \
          git rev-parse --abbrev-ref HEAD | egrep --ignore-case "^wip/" \
            && echo 'Branch name contains wip. Skipping commit msg check' \
            || cz check --commit-msg-file .git/COMMIT_EDITMSG
        "
      pass_filenames: false
      always_run: true
