# get artifacts:
# docs
# package
# testing (pytest-html, coverage, etc)

# if is push on master (or pr success)
publish to drytoml.readthedocs
publish to pypi/drytoml

# if is push on master (or pr success)
publish to staging.drytoml.readthedocs
publish to test.pypi/drytoml
