---
name: Bug report
about: Something is not working correctly.
title: ""
labels: "S: needs triage, type: bug"
issue_body: true  # default: true, adds a classic WSYWIG textarea, if on
inputs:
- type: description
  attributes:
    value: "**Environment**"
- type: input
  attributes:
    label: pip version
    required: true
- type: input
  attributes:
    label: Python version
    required: true
- type: input
  attributes:
    label: OS
    required: true
- type: input
  attributes:
    label: Processor Architecture (eg from `uname -a`, or `lscpu`)
    required: true
- type: textarea
  attributes:
    label: Additional information
    description: >-
      Feel free to add more information about your environment here (eg specific hw).

- type: textarea
  attributes:
    label: Description
    description: >-
      A clear and concise description of what the bug is.

- type: textarea
  attributes:
    label: Expected behavior
    description: >-
      A clear and concise description of what you expected to happen.

- type: textarea
  attributes:
    label: How to Reproduce
    description: >-
      Describe the steps to reproduce this bug.
    value: |
      1. Get package from '...'
      2. Then run '...'
      3. An error occurs.

- type: textarea
  attributes:
    label: Output
    description: >-
      Paste the output of the steps above, including the commands
      themselves and their output/traceback etc.
    value: |
      ```console

      ```
