name: Docs

on:
  pull_request:

jobs:

  Sphinx:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v1
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install deps
        # TODO simplyfy this when poetry1.2 lands
        run: |
          pip install .[docs]

      - name: Gather Apidocs
        run: |
          sphinx-apidoc \
            --templatedir=docs/src/templates \
            --separate \
            --module-first \
            --force \
            -o docs/src/apidoc src/drytoml

      - name: Build with Sphinx
        run: |
          sphinx-build docs/src docs/build
